kafka:
  bootstrap-servers: localhost:9092
  topic:
    signal: nodered
    sensor: test
server:
  port: 9004
  
spring :
   datasource:
         url: jdbc:mysql://localhost:3306/meta_data_handler?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
         username: root
         password: root   
         
jpa:
    hibernate:
          ddl-auto: update 
          



                 
management:
   endpoints:
      web:
      cors:
      allowed-origins: "*"
      allowed-methods: GET,POST